#!/bin/sh

fix='cp -- "$0" "$(dirname -- "$0")/$(jq -r .messages[0].ts "$0")0.json"' git rebase --root --exec 'find -name latest.json -exec sh -c "$fix" {} \;; git add .; git commit --amend --no-edit'
