#!/bin/sh -eu
cd -- "$(dirname -- "$(realpath -- "$0")")"

users="$(jq -r '[
  (input_filename | split("/") | .[-1] | split(".") | .[0]),
  .results[].name
  ]| @tsv' data/meta/*/users/*.json)"

mkdir -p chats
jq -r '(
  ("data/messages/" + .team.domain) as $team |
  (.channels[] | [$team + "/channels/" + .id, .name]),
  (.channels[] | [$team + "/mpims/" + .id, .name]),
  (.mpims[] | [$team + "/mpims/" + .id, .name]),
  (.ims[] | [$team + "/ims/" + .id, .user])
  ) | @tsv' data/meta/*/boot.json |
  while read -r path channel; do
    if user="$(printf '%s' "$users" | grep -F "$channel")"; then
      label="$user"
    else
      label="$channel"
    fi
    label="${label#*"$(printf '\t')"}"
    prefix="${path%/*}"
    prefix="${prefix##*/}"
    set -x
    out="chats/$prefix-$label.txt"
    ./format.js "$path" >"$out" || :
    set +x
    if ! test -s "$out"; then
      rm -- "$out"
    else
      date_regexp='^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]\.[0-9][0-9][0-9]Z,'
      touch -d "$(grep -Eo "$date_regexp" -- "$out" | tail -n 1 | head -c -2)" -- "$out"
    fi
  done
